### ISSUE TITLE
编译失败提示

### ISSUE THREAD

**Issue by find0day** [axetroy/go-upload#1]
go build -v -o ./bin/server
github.com/axetroy/go-upload/http
# github.com/axetroy/go-upload/http
http/http.go:31:27: cannot assign 2 values to 3 variables
http/http.go:34:13: undefined: uploader.Resolve
make: *** [all] Error 2

**Comment by axetroy** [comment]
@find0day 
这个昨晚我update了一下，修复了

**Comment by find0day** [comment]
@axetroy 
update 了，非常好用。谢谢！
